version: '3'
services:
  postgres:
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - skynet

  chat-node-server:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/home/node/app
    depends_on:
      - postgres
    networks:
      - skynet
    command: ['npm', 'start']

  migration:
    image: rooksgc/chat-node-server
    volumes:
      - .:/home/node/app
    command:
      [
        './wait-for-it.sh',
        'postgres:5432',
        '--',
        'npm',
        'run',
        'db:migrate:prod'
      ]
    links:
      - postgres
      - rooksgc/chat-node-server
    depends_on:
      - postgres
      - rooksgc/chat-node-server
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
