version: '3'
services:
  postgres:
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - skynet

  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - skynet
    command: ['npm', 'run', 'dev']

  migration:
    image: app
    volumes:
      - .:/app
    command:
      [
        './wait-for-it.sh',
        'postgres:5432',
        '--',
        'npm',
        'run',
        'db:migrate:dev'
      ]
    links:
      - postgres
      - app
    depends_on:
      - postgres
      - app
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
